from tkinter import *
from tkinter import messagebox
from tkinter.scrolledtext import ScrolledText
from tkinter.ttk import Combobox
from tkinter import filedialog
import os
x=Tk()
x.title("ninja")
x.geometry("500x500")
# x.attributes("-alpha",0.5) # alpha range 0-1
# x.attributes("-topmost",0)
# value 0 or 1
# print("start")
# l=Label(x,text="name")  # they are called widgets
# l.grid(row=1,column=1)
# l1=Label(x,text="age",background="yellow",foreground="red",width=10,height=9,anchor="center")
# l1.grid(row=2,column=2)
# l2=Label(x,text="age",background="blue",foreground="red",width=10,height=9,anchor="se")
# l2.grid(row=3,column=3)
# l111=Label(x,text="age",background="indigo",foreground="red",width=10,height=9,anchor="w")
# l111.grid(row=4,column=4)
# l12=Label(x,text="age",background="pink",foreground="red",width=10,height=9,anchor="n")
# l12.grid(row=5,column=5)
# l13=Label(x,text="age",background="orange",foreground="red",width=10,height=9,anchor="ne")
# l13.grid(row=6,column=6)
# l1=Label(x,text="age",background="yellow",foreground="red",width=10,height=9,anchor="center",font=("arial",10,"bold"),cursor="circle",padx=20) 
# l1.grid(row=1,column=1)
# l1=Label(x,text="age",background="green",foreground="red",width=10,height=9,anchor="center",font=("arial",10,"italic"),cursor="clock",pady=90)
# l1.grid(row=2,column=2)
# l1=Label(x,text="age",background="black",foreground="red",width=10,height=9,anchor="center",font=("arial",10,"underline"),cursor="plus")
# l1.grid(row=4,column=4)
# l1=Label(x,text="age",background="purple",foreground="red",width=10,height=9,anchor="center",font=("arial",10,"overstrike"))
# l1.grid(row=3,column=3)
# e1=Entry(x)
# e1.grid(row=3,column=3)
# l1=Label(x,text="name",bg="red")
# l1.grid(row=1,column=1)
# e1=Entry(x)
# e1.grid(row=1,column=2)
# l1=Label(x,text="age",bg="green")
# l1.grid(row=2,column=1)
# e1=Entry(x)
# e1.grid(row=2,column=2)
# l1=Label(x,text="salary",bg="violet")
# l1.grid(row=3,column=1)
# e1=Entry(x)
# e1.grid(row=3,column=2)
# l1=Label(x,text="place",bg="indigo")
# l1.grid(row=4,column=1)
# e1=Entry(x)
# e1.grid(row=4,column=2)
# l1=Label(x,text="password",bg="black")
# l1.grid(row=5,column=1)
# e1=Entry(x,show="*",justify="center",width=30)
# e1.grid(row=5,column=2)
# l1=Label(x,text="password",bg="purple")
# l1.grid(row=6,column=1)
# e1=Entry(x,justify="right",bd=5)
# e1.grid(row=6,column=2)
# l1=Label(x,text="password",bg="aqua")
# l1.grid(row=7,column=1)
# e1=Entry(x,justify="left")
# e1.grid(row=7,column=2)
# l=Label(x,text="name")
# l.grid(row=1,column=1)
# e=Entry(x)
# e.grid(row=1,column=2)
# b=Button(x,text="click",bg="aqua",fg="navy",activebackground="black",activeforeground="red")
# b.grid(row=2,column=1)
# b1=Button(x,text="click")
# b1.grid(row=2,column=1)
# b1=Button(x,text="click",font="aerial 10 bold")
# b1.grid(row=2,column=1)
# b1=Button(x,text="click",bg="navy",fg="crimson")
# b1.grid(row=3,column=1)
# b1=Button(x,text="click for width",width=40)
# b1.grid(row=4,column=1)
# b1=Button(x,text="click for height",height=4)
# b1.grid(row=5,column=1)
# b1=Button(x,text="click bg",activebackground="coral")
# b1.grid(row=6,column=1)
# b1=Button(x,text="click fg",activeforeground="teal")
# b1.grid(row=7,column=1)
# b1=Button(x,text="click bd",bd=10)
# b1.grid(row=8,column=1)
# b1=Button(x,text="click disabled",state=DISABLED)
# b1.grid(row=9,column=1)
# b1=Button(x,text="click padx",padx=40)
# b1.grid(row=10,column=1)
# b1=Button(x,text="click pady",pady=40)
# b1.grid(row=11,column=1)
# b1=Button(x,text="click sunken",relief=SUNKEN,bd=10,bg="gold")
# b1.grid(row=12,column=1)
# b1=Button(x,text="click ridge",relief=RIDGE,bd=10,bg="darkturquoise")
# b1.grid(row=13,column=1)
# b1=Button(x,text="click groove",relief=GROOVE,bd=10,bg="purple")
# b1.grid(row=14,column=1)
# b1=Button(x,text="click raised",relief=RAISED,bd=10,bg="orange")
# b1.grid(row=15,column=1)
# b1=Button(x,text="click flat",relief=FLAT,bd=10,bg="tomato")
# b1.grid(row=16,column=1)
# x.configure(bg="aqua")
# l1=Label(x,text="name")
# l1.grid(row=1,column=1)
# e=Entry(x)
# e.grid(row=1,column=2)
# l=Label(x,text="")
# l.grid(row=3,column=1)
# def click():
#     z=e.get()
#     print(z)
#     print("working")
#     x.configure(bg="navy")
#     l.configure(text="changed")
#     l1.configure(text="changed win")
#     l1.destroy()
#     b.destroy()
# b=Button(x,text="click",command=click)
# b.grid(row=5,column=3)
# a=StringVar()
# e1=Entry(x,textvariable=a)
# e1.grid(row=1,column=2)
# def click():
#     a.set("ammu")
#     z=e1.get()
#     print(z)
#     print("working")
#     x.configure(bg="pink")
    

    
# b=Button(x,text="click",command=click)
# b.grid(row=5,column=3)
# l=Label(x,text="name")
# l.place(x=50,y=100)
# l=Label(x,text="age")
# l.place(x=100,y=150)
# l=Label(x,text="salary")
# l.place(x=150,y=200)
# l=Label(x,text="password")
# l.place(x=200,y=250)
# l=Label(x,text="name")
# l.pack()
# l=Label(x,text="age")
# l.pack()
# l=Label(x,text="salary")
# l.pack()
# l=Label(x,text="password")
# l.pack()
# w=StringVar()
# l=Label(x,text="first number")
# l.pack()
# e=Entry(x)
# e.pack()
# l1=Label(x,text="second number")
# l1.pack()
# e1=Entry(x)
# e1.pack()
# l2=Label(x,text="result")
# l2.pack()
# e2=Entry(x,textvariable=w)
# e2.pack()

# def win():
#     x1=int(e.get())
#     y=int(e1.get())
#     z=x1+y
    
#     w.set(z)
    
    
# b=Button(x,text="click",command=win)
# b.pack()

# x.mainloop()
# # print("stop")
#---------------------------------------------
# p=IntVar()
# # p=StringVar()
# r1=Radiobutton(x,text="male",variable=p,value=1)
# r1.grid(row=1,column=2)
# r1=Radiobutton(x,text="female",variable=p,value=2)
# r1.grid(row=2,column=2)
# x.mainloop()
# l=Label(x,text="first number")
# l.grid(row=2,column=3)
# def results():
    # messagebox.showinfo("alert","information")
    # messagebox.showerror("alert","error")
    # messagebox.showwarning("alert","warning")
#     q=messagebox.askokcancel("question","ask ok or cancel")
#     if q:
#         l.configure(text="you clicked ok")
#     else:
#         l.configure(text="you clicked cancel")
    
#     messagebox.askquestion("question","ok or cancel")
#     messagebox.askretrycancel("question","ok or cancel")
#     messagebox.askyesno("question","ok or cancel")
#     messagebox.askyesnocancel("question","ok or cancel")
# b=Button(x,text="click",command=results)
# b.grid(row=1,column=2)
# c1=Checkbutton(x, text="english")
# c1.grid(row=1,column=1)
# c2=Checkbutton(x, text="malayalam")
# c2.grid(row=2,column=1)
# c3=Checkbutton(x, text="arabic")
# c3.grid(row=3,column=1)
# s=Spinbox(x,from_=1,to=10,bg="aqua")
# s.grid(row=4,column=1)=
# ss=ScrolledText(x,width=30,height=20)
# ss.grid(row=10,column=5)
# cc=Combobox(x)
# cc["values"]=["python","anaconda","viper"]
# cc.current(0)
# cc.grid(row=11,column=7)
# filename=filedialog.askopenfilename()
# print(filename)
# p=os.path.basename(filename)
# print(p)
# def click():
#     filename=filedialog.askopenfilename()

#     p=os.path.basename(filename)

#     l.configure(text=p)
    
# b=Button(x,text="select",command=click)
# b.grid(row=1,column=1)
# l=Label(x,text="no file chosen")
# l.grid(row=1,column=2)

# def click():
#     filename=filedialog.askopenfilename()
    
# ---------------------------------------------------------
    
# l=Label(x,text=" choose anyone")
# l.grid(row=1,column=2)
# new=Menu(x)
# new_1=Menu(new,tearoff=False)      ## tearoff is used to remove -------- line
# new.add_cascade(label="file",menu=new_1)
# new_1.add_command(label="new text file",command=quit)
# # new_1.add_command(label="new file",command=click)
# new_1.add_command(label="new window")
# new_1.add_separator()
# new_1.add_command(label="open file")
# new_1.add_command(label="open folder")
# new.add_cascade(label="edit")
# new.add_cascade(label="selection")
# new.add_cascade(label="view")
# new.add_cascade(label="go")

# x.configure(menu=new)
# img=PhotoImage(file="./zootopia.png")
# # img=PhotoImage(file=r"C:\Users\Dell\Downloads\zootopia.png")
# x.iconphoto(True,img)
# canvas=Canvas(x,width=800,height=800)
# canvas.pack()
# canvas.create_image(100,100,image=img)
# canvas.create_text(200,40,text="welcome to tkinter")



# for any type of images type these codes in the terminal
# pip install pillow
# from PIL import Image
# img=Image.open("my.jpg")
# img.save("my.png","PNG")
# f1=Frame(x,highlightbackground="aqua",highlightthickness=50)
# f1.grid(row=0,column=0,ipadx=200,ipady=200,padx=40,pady=40)
# l=Label(f1,text="",bg="teal",image=img)
# l.grid(row=1,column=5)
# l=Label(f1,text="age",bg="yellow")
# l.grid(row=2,column=5)
# l=Label(f1,text="name",bg="brown")
# l.grid(row=3,column=5)

# l=Label(x,text="name",bg="green")
# l.pack(fill=X,expand=True)
# l=Label(x,text="name",bg="blue")
# l.pack(fill=Y,expand=True)

# l=Label(x,text="name",bg="green")
# l.pack(fill=BOTH,expand=True)
# l=Label(x,text="name",bg="blue")
# l.pack(fill=BOTH,expand=True)

# l=Label(x,text="name",bg="green")
# l.pack(side=RIGHT)
# l=Label(x,text="name",bg="blue")
# l.pack(side=LEFT)

# l=Label(x,text="name",bg="green")
# l.pack(side=)
# l=Label(x,text="name",bg="blue")
# l.pack(side=BOTTOM)

l=Label(x,text="name",bg="green")
l.pack(fill=BOTH,expand=True,side=BOTTOM)
l=Label(x,text="name",bg="blue")
l.pack(fill=BOTH,expand=True,side=TOP)

# l=Label(x,text="name",bg="green")
# l.pack(fill=BOTH,expand=True,side=RIGHT)
# l=Label(x,text="name",bg="blue")
# l.pack(fill=BOTH,expand=True,side=LEFT)

# def insert():
    
#     global e
#     # e.insert(0,"hello\n")
#     s.insert(1.0,"hello\n")
#     s.insert(2.0,"helo\n")
# def delete():
#     # e.delete(0,END)
#     # s.delete(3.0,END)
#     # s.delete(1.1,END)
#     # s.delete(1.0,END)
#     s.delete(2.0,END)

# s=ScrolledText(x,width=30,height=20,bg="thistle")
# s.grid(row=3,column=3)
# e=Entry(x)
# e.grid(row=1,column=2)
# b=Button(x,text="insert",bg="violet",command=insert)
# b.grid(row=1,column=1)
# b=Button(x,text="delete",bg="yellow",command=delete)
# b.grid(row=2,column=1)

# progressive bar



x.mainloop()
